server:
  port: 8080

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productdb?serverTimezone=UTC
    username: root
    password: 381254lrj
  main:
    banner-mode: off
#开启mp的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


    global-config:
      banner: false

#可以用命令行生成64位密钥： openssl rand -hex 64
jwt:
  secret: db9d654c4860d4d37406d1ffcd92be5756a9ea94c03464aba0e475dc88932fee2278a23f6e6953a24d089ad09d99ac9d07ebd223a7f264fa2a7bea8a779c7946